spring:
  application:
    name: questio

  # Configuração do Banco de Dados
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/questio
    username: root
    password: # Senha vazia (padrão XAMPP/WAMP) ou coloque a sua aqui

  # Configuração do Hibernate/JPA
  jpa:
    hibernate:
      ddl-auto: update # Cuidado: 'update' mantém os dados, 'create-drop' apaga tudo ao reiniciar

  # --- Configuração de E-mail (Gmail) ---
  mail:
    host: smtp.gmail.com
    port: 587
    username: enviosquestio@gmail.com
    password: trxtgqefnkmqyqib # Sua Senha de App
    properties:
      mail:
        smtp:
          connectiontimeout: 5000 # 5 segundos para conectar
          timeout: 5000           # 5 segundos para ler
          writetimeout: 5000
          auth: true
          starttls:
            enable: true

# Configuração do Servidor (Encoding UTF-8 para não quebrar acentos)
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true